import {
    IonApp,
    IonContent,
    IonIcon,
    IonItem,
    IonLabel,
    IonList,
    IonListHeader,
    IonMenu,
    IonMenuToggle,
    IonNote,
    IonRouterOutlet,
    IonSplitPane,
  } from '@ionic/vue';
  import { ref } from 'vue';
  import {
    alertCircleOutline,
    alertCircleSharp,
    archiveOutline,
    archiveSharp,
    analyticsOutline,
    analyticsSharp,
    infiniteOutline,
    infiniteSharp,
    peopleOutline,
    peopleSharp,
    receiptOutline,
    receiptSharp,
    cardOutline,
    cardSharp,
    bookmarkOutline,
    bookmarkSharp,
    calendarOutline,
    calendarSharp,
    cameraOutline,
    hammerOutline,
    logOutOutline,
    logOutSharp,
    readerOutline,
    readerSharp,
    settingsOutline,
    settingsSharp,
    leafOutline,
    leafSharp,
    hammerSharp,
    cameraSharp,
    paperPlaneOutline,
    paperPlaneSharp,
    trashOutline,
    trashSharp,
    warningOutline,
    warningSharp,
    home,
    homeOutline,
    homeSharp,
    bagHandleOutline,
    bagHandleSharp,
    timeOutline,
    timeSharp,
      giftOutline,
      giftSharp,
  } from 'ionicons/icons';
const auctioneerPages = [
    {
      title: 'Stock List',
      url: '/folder/stock',
      iosIcon: hammerOutline,
      mdIcon: hammerSharp,
    },
    {
      title: 'Auction Schedules',
      url: '/folder/schedules',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    },
    {
      title: 'Auction Sessions',
      url: '/folder/sessions',
      iosIcon: readerOutline,
      mdIcon: readerSharp,
    },
    {
      title: 'Grower Clubs',
      url: '/folder/growerclubs',
      iosIcon: cameraOutline,
      mdIcon: cameraSharp,
    }, 
    {
      title: 'Camera',
      url: '/folder/camera',
      iosIcon: cameraOutline,
      mdIcon: cameraSharp,
    },
    {
      title: 'Settings',
      url: '/folder/settings',
      iosIcon: settingsOutline,
      mdIcon: settingsSharp,
    },
  ];
  const buyerPages = [
   {
      title: 'View Auction',
      url: '/folder/buyer/view',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    }, 
  {
      title: 'Auction Schedules',
      url: '/folder/buyer/schedules',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    },
    {
    title: 'Auction Sessions',
    url: '/folder/buyer/sessions',
    iosIcon: readerOutline,
    mdIcon: readerSharp,
    },
    {
      title: 'Purchases',
      url: '/folder/buyer/purchases',
      iosIcon: receiptOutline,
      mdIcon: receiptSharp,
    },
    {
    title: 'Reverse Bid',
    url: '/folder/buyer/reversals',
    iosIcon: infiniteOutline,
    mdIcon: infiniteSharp,
    },
    {
      title: 'Launch Complaint',
      url: '/folder/buyer/complaints',
      iosIcon: alertCircleOutline,
      mdIcon: alertCircleSharp,
    },
    {
      title: 'Payments',
      url: '/folder/buyer/payments',
      iosIcon: cardOutline,
      mdIcon: cardSharp,
    },
    {
      title: 'Settings',
      url: '/folder/settings',
      iosIcon: settingsOutline,
      mdIcon: settingsSharp,
    },
  ];
  const farmerPages = [
    {
      title: 'Home',
      url: '/folder/home',
      iosIcon: home,
      mdIcon: homeSharp,
    },
    {
      title: 'Auction Schedules',
      url: '/folder/schedules',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    },
    {
      title: 'Auction Session',
      url: '/folder/session',
      iosIcon: hammerOutline,
      mdIcon: hammerSharp,
    },
    {
      title: 'Consignments',
      url: '/folder/consignments',
      iosIcon: leafOutline,
      mdIcon: leafSharp,
    },
    {
      title: 'Bales',
      url: '/folder/bale',
      iosIcon: giftOutline,
      mdIcon: giftSharp,
    },
    {
      title: 'My Stock',
      url: '/folder/consignment/:id',
      iosIcon: bagHandleOutline,
      mdIcon: bagHandleSharp,
    },
    {
      title: 'History',
      url: '/folder/history',
      iosIcon: timeOutline,
      mdIcon: timeSharp,
    },
  ];
  const adminPages = [
    {
      title: 'Dashboard',
      url: '/folder/Dashboard',
      iosIcon: homeOutline,
      mdIcon: homeSharp,
    },
    {
      title: 'Categories',
      url: '/folder/Categories',
      iosIcon: readerOutline,
      mdIcon: readerSharp,
    },
    {
      title: 'Bids',
      url: '/folder/Bids',
      iosIcon: hammerOutline,
      mdIcon: hammerSharp,
    },
    {
      title: 'Payments',
      url: '/folder/Payments',
      iosIcon: cardOutline,
      mdIcon: cardSharp,
    },
    {
      title: 'Complaints',
      url: '/folder/Complaints',
      iosIcon: readerOutline,
      mdIcon: readerSharp,
    },
    {
      title: 'Analytics and Reports',
      url: '/folder/Reporting',
      iosIcon: analyticsOutline,
      mdIcon: analyticsSharp,
    },
    {
      title: 'User Management',
      url: '/folder/User Management',
      iosIcon: peopleOutline,
      mdIcon: peopleSharp,
    },
    {
      title: 'Settings',
      url: '/folder/Settings',
      iosIcon: settingsOutline,
      mdIcon: settingsSharp,
    },
  ];
  const guestPages = [
    {
      title: 'Dashboard',
      url: '/folder/Dashboard',
      iosIcon: homeOutline,
      mdIcon: homeSharp,
    },
    {
      title: 'Categories',
      url: '/folder/Categories',
      iosIcon: readerOutline,
      mdIcon: readerSharp,
    },
    {
      title: 'Bids',
      url: '/folder/Bids',
      iosIcon: hammerOutline,
      mdIcon: hammerSharp,
    },
    {
      title: 'Payments',
      url: '/folder/Payments',
      iosIcon: cardOutline,
      mdIcon: cardSharp,
    },
    {
      title: 'Complaints',
      url: '/folder/Complaints',
      iosIcon: readerOutline,
      mdIcon: readerSharp,
    },
    {
      title: 'Analytics and Reports',
      url: '/folder/Reporting',
      iosIcon: analyticsOutline,
      mdIcon: analyticsSharp,
    },
    {
      title: 'User Management',
      url: '/folder/User Management',
      iosIcon: peopleOutline,
      mdIcon: peopleSharp,
    },
    {
      title: 'Settings',
      url: '/folder/Settings',
      iosIcon: settingsOutline,
      mdIcon: settingsSharp,
    },
  ];

export {auctioneerPages, buyerPages, farmerPages, adminPages, guestPages};